build:
  version: "1.0"

cart:
  message: "Welcome to Ecommerce Cart Service related local APIs "
  contactDetails:
    name: "Mostafa - Developer"
    email: "cartlocal@ecommerce.com"
  onCallSupport:
    - (+20) 01555331990
