# userservice 8080
# cartservice 8081
# orderservice 8082
# productservice 8083
# inventoryservice 8084
# paymentservice 8085

services:
  ecommercedb:
    container_name: "e-commercedb"
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    networks:
      - ecommerce

  rabbitmq:
    image: rabbitmq:3.12-management
    hostname: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - ecommerce

  configservice:
    image: "sasa274/ecommerce-configservice:v2"
    container_name: "e-configservice"
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --slient localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce


  userservice:
    image: "sasa274/ecommerce-userservice:v2"
    container_name: "e-userservice"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_APPLICATION_NAME: "userservice"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
      SPRING_PROFILES_ACTIVE: default

  cartservice:
    image: "sasa274/ecommerce-cartservice:v2"
    container_name: "e-cartservice"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_APPLICATION_NAME: "cartservice"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
      SPRING_PROFILES_ACTIVE: default

  orderservice:
    image: "sasa274/ecommerce-orderservice:v2"
    container_name: "e-orderservice"
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_APPLICATION_NAME: "orderservice"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
      SPRING_PROFILES_ACTIVE: default

  productservice:
    image: "sasa274/ecommerce-productservice:v2"
    container_name: "e-productservice"
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_APPLICATION_NAME: "productservice"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
      SPRING_PROFILES_ACTIVE: default


  inventoryservice:
    image: "sasa274/ecommerce-inventoryservice:v2"
    container_name: "e-inventoryservice"
    ports:
      - "8084:8084"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_APPLICATION_NAME: "inventoryservice"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
      SPRING_PROFILES_ACTIVE: default

  paymentservice:
    image: "sasa274/ecommerce-paymentservice:v2"
    container_name: "e-paymentservice"
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
      configserver:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_APPLICATION_NAME: "paymentservice"
      SPRING_CONFIG_IMPORT: "configserver:http://configservice:8071/"
      SPRING_PROFILES_ACTIVE: default

networks:
  ecommerce:
    driver: bridge