# userservice 8080
# cartservice 8081
# orderservice 8082
# productservice 8083
# inventoryservice 8084
# paymentservice 8085

services:
  ecommercedb:
    container_name: "e-commercedb"
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  configservice:
    image: "sasa274/ecommerce-configservice:v2"
    container_name: "e-configservice"
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --slient localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends: 
      file: common-config.yml
      service: microservice-base-config 


  userservice:
    image: "sasa274/ecommerce-userservice:v2"
    container_name: "e-userservice"
    ports:
      - "8080:8080"
    depends_on:
      ecommercedb:
        condition: service_healthy
      configservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "userservice"
    extends:
      file: common-config.yml
      service: microservice-configserver-config
      

  cartservice:
    image: "sasa274/ecommerce-cartservice:v2"
    container_name: "e-cartservice"
    ports:
      - "8081:8081"
    depends_on:
      ecommercedb:
        condition: service_healthy
      configservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "cartservice"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  orderservice:
    image: "sasa274/ecommerce-orderservice:v2"
    container_name: "e-orderservice"
    ports:
      - "8082:8082"
    depends_on:
      ecommercedb:
        condition: service_healthy
      configservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "orderservice"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  productservice:
    image: "sasa274/ecommerce-productservice:v2"
    container_name: "e-productservice"
    ports:
      - "8083:8083"
    depends_on:
      ecommercedb:
        condition: service_healthy
      configservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "productservice"


  inventoryservice:
    image: "sasa274/ecommerce-inventoryservice:v2"
    container_name: "e-inventoryservice"
    ports:
      - "8084:8084"
    depends_on:
      ecommercedb:
        condition: service_healthy
      configservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "inventoryservice"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  paymentservice:
    image: "sasa274/ecommerce-paymentservice:v2"
    container_name: "e-paymentservice"
    ports:
      - "8085:8085"
    depends_on:
      ecommercedb:
        condition: service_healthy
      configservice:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: "paymentservice"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  ecommerce:
    driver: bridge