# userservice 8080
# cartservice 8081
# orderservice 8082
# productservice 8083
# inventoryservice 8084
# paymentservice 8085

services:
  ecommercedb:
    container_name: "e-commercedb"
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 10s
      start_period: 10s
    networks:
      - ecommerce

  userservice:
    image: "sasa274/ecommerce-userservice:v1"
    container_name: "e-userservice"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

  cartservice:
    image: "sasa274/ecommerce-cartservice:v1"
    container_name: "e-cartservice"
    ports:
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

  orderservice:
    image: "sasa274/ecommerce-orderservice:v1"
    container_name: "e-orderservice"
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

  productservice:
    image: "sasa274/ecommerce-productservice:v1"
    container_name: "e-productservice"
    ports:
      - "8083:8083"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

  inventoryservice:
    image: "sasa274/ecommerce-inventoryservice:v1"
    container_name: "e-inventoryservice"
    ports:
      - "8084:8084"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

  paymentservice:
    image: "sasa274/ecommerce-paymentservice:v1"
    container_name: "e-paymentservice"
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - ecommerce
    depends_on:
      ecommercedb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://ecommercedb:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

networks:
  ecommerce:
    driver: bridge