spring:
  application:
    name: "cartservice"
  profiles:
    active: "default"
  datasource:
    url: jdbc:mysql://localhost:3307/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    openfeign:
      circuit:
        enabled: true
  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "cartservice"
    description: "Cart Service"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness:
      enabled: true
    liveness:
      enabled: true
    
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
        
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

server:
  port: 8081




resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000


resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - java.lang.NullPointerException
