spring:
  application:
    name: gatewayservice
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
  security:
    oauth2:
      client:
        registration:
          spring:
            provider: spring
            client-id: client
            client-secret: "asd" # Added {noop} for consistency
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://localhost:8072/login/oauth2/code/spring"
            scope:
              - user.read
              - openid
        provider:
          spring:
            issuer-uri: http://localhost:8097

      resourceserver:
        jwt:
          issuer-uri: http://localhost:8097

logging:
  level:
    org:
      springframework:
        security:
          oauth2: TRACE
          web: TRACE

info:
  app:
    name: gatewayservice
    description: "Gateway Service"
    version: "1.0.0"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
